
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[override]]
  version = "0.9.1"
  name = "github.com/emersion/go-message"

[[constraint]]
  name = "github.com/katzenpost/core"
  version = "0.0.7"

[[constraint]]
  name = "github.com/katzenpost/mailproxy"
  version = "0.0.6"

[[constraint]]
  name = "github.com/katzenpost/registration_client"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
