
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  name = "github.com/katzenpost/core"
  version = "0.0.4"

[[constraint]]
  name = "github.com/katzenpost/mailproxy"
  version = "0.0.3"

[[constraint]]
  name = "github.com/katzenpost/registration_client"
  version = "0.0.0"

[prune]
  go-tests = true
  unused-packages = true
